[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
futurity = "GMaCbLs28PYev8gJoPCb1XSHaLpufNqGbNeXEz5c7jzv"

[programs.devnet]
futurity = "GMaCbLs28PYev8gJoPCb1XSHaLpufNqGbNeXEz5c7jzv"

[programs.mainnet]
futurity = "GMaCbLs28PYev8gJoPCb1XSHaLpufNqGbNeXEz5c7jzv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf -- --nocapture"
