[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
futurity = "2PswCESR7U3MF9CL3B89qQFnJ9tac6ucGVQR3Zm7xeGP"

[programs.devnet]
futurity = "2PswCESR7U3MF9CL3B89qQFnJ9tac6ucGVQR3Zm7xeGP"

[programs.mainnet]
futurity = "2PswCESR7U3MF9CL3B89qQFnJ9tac6ucGVQR3Zm7xeGP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf -- --nocapture"
